# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# To run and deploy to beta channel
# bundle exec fastlane deploy
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :bump_version_code do
    versionCode = File.read("metadata/versionCode").to_i
         versionCode = versionCode +1

         f = File.new("metadata/versionCode", "w")
         f.write(versionCode)
         f.close
         versionCode
  end

  desc "Deploy a new version to the Google Play"
  lane :prod do
     versionCode = bump_version_code

     sh("flutter","build","appbundle","--build-number=#{versionCode}")

     upload_to_play_store(
        track: 'production',
        # apk: '../build/app/outputs/apk/release/app-release.apk',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        json_key: '../android/{{name.snakeCase()}}_fastlane.json'
      )

      slack(
         slack_url: 'https://hooks.slack.com/services/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',
         message: "Google Prod - Version #{versionCode} of {{name.titleCase()}} was published"
      )
  end

  desc "Deploy a new version to the beta test track of Google Play"
  lane :beta do
     versionCode = bump_version_code

     sh("flutter","build","appbundle","--build-number=#{versionCode}")

     upload_to_play_store(
        track: 'beta',
        # apk: '../build/app/outputs/apk/release/app-release.apk',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
      )

      slack(
        slack_url: 'https://hooks.slack.com/services/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',
        message: "Google Beta - Version #{versionCode} of {{name.titleCase()}} was published"
      )
  end
end

     # Build apk
=begin
    gradle(
        task: 'assemble',
        build_type: 'Release',
        properties: { 'versionCode' => versionCode }
     )
=end

     # Build appbundle
=begin
     build_android_app(
          task: 'bundle',
          build_type: 'Release',
          properties: { 'versionCode' => versionCode }
     )
=end